coffe_shop/coffe_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('products.urls')),
    path('usuarios/', include('users.urls')),
    path('pedidos/', include('orders.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coffe_shop/orders/urls.py
from django.urls import path

from .views import MyOrderView, CreateOrderProductView, OrderAPI

urlpatterns = [
    path("mi-orden", MyOrderView.as_view(), name="my_order"),
    path("agregar-producto", CreateOrderProductView.as_view(), name="add_product"),
    path(
        "api", OrderAPI.as_view(), name="order_product_api"
    ),  # API para obtener las ordenes activas de los usuarios
]

coffe_shop/products/urls.py
from django.urls import path
from .views import ProductFromView, ProductListView, ProductListAPI

urlpatterns = [
    path('', ProductListView.as_view(), name='list_product'),
    path('api/', ProductListAPI.as_view(), name='list_product_api'),
    path('agregar/', ProductFromView.as_view(), name='add_product'),
]

coffe_shop/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("registro/", RegisterView.as_view(), name="register"),
]

coffe_shop/orders/models.py
from django.db import models
from django.contrib.auth.models import User

from products.models import Product

# Modelo de pedidos
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True) #saber si la orden esta activa o agregando productos
    order_date = models.DateTimeField(auto_now_add=True) #fecha de creacion al momento de registrar la orden

    def __str__(self):
        return f'order {self.id} by {self.user}'
    
# Modelo para guardar la orden, el producto y la cantidad
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE) #relacion con el modelo de orden
    product = models.ForeignKey(Product, on_delete=models.PROTECT) #si la orden esta lista y el producto se elimina, necesitamos dejar la orden en su estado anterior
    quantity = models.IntegerField() 

    def __str__(self):
        return f'{self.order} - {self.product}'

coffe_shop/products/models.py
from django.db import models


class Product(models.Model):
    # verbose_name --> como queremos que nuestro campo se vea en el usuario final o en el admin de django
    # el cual nos permite administrador los datos de nuestro modelo
    name = models.TextField(max_length=200, verbose_name='nombre')
    description = models.TextField(max_length=300, verbose_name='descripcion')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='precio')
    available = models.BooleanField(default=True, verbose_name='disponible')
    photo = models.ImageField(upload_to='logos', null=True, blank=True, verbose_name='foto') # parametros para permitir subir un producto sin foto

    def __str__(self):
        return self.name

coffe_shop/orders/forms.py
from django.forms import ModelForm
from .models import OrderProduct

# Formulario para mis pedidos en donde esta la orden, producto y la cantidad
class OrderProductForm(ModelForm):
  class Meta:
    model = OrderProduct
    fields = ['product'] # Solo utilizamos el producto

coffe_shop/products/forms.py
from django import forms
from .models import Product


# Formulario para el modelo Products
class ProductForm(forms.Form):
    name = forms.CharField(max_length=200, label="Nombre")
    description = forms.CharField(max_length=300, label="Descripción")
    price = forms.DecimalField(max_digits=10, decimal_places=2, label="Precio")
    available = forms.BooleanField(initial=True, label="Disponible", required=False)
    photo = forms.ImageField(label="Foto", required=False)

    # metodo que guarda la informacion del formulario cuando el usuario haga submit y crear estos datos en la base de datos
    def save(self):
        Product.objects.create(
            # cleaned_data --> informacion limpia desde el request del usuario
            name = self.cleaned_data['name'],
            description = self.cleaned_data['description'],
            price = self.cleaned_data['price'],
            available = self.cleaned_data['available'],
            photo = self.cleaned_data['photo'],
        )

coffe_shop/orders/views.py
from django.views.generic import DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from rest_framework.views import APIView
from rest_framework.response import Response

from .models import Order
from .forms import OrderProductForm
from .serializers import OrderSerializer

# Vista que nos muestra en detalle la orden que hicimos
# Con LoginRequiredMixin, obligamos a que el usuario tenga una sesion iniciada para acceder a la vista
class MyOrderView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'orders/my_order.html'
    context_object_name = 'order' # Acceder dentro del html

    def get_object(self, queryset=None):
        return Order.objects.filter(is_active = True, user=self.request.user).first() #filter devuelve una lista y no un objeto, por eso usamos first() para transformarlo en un elemento y poder usarlo en el detailview

# Vista del boton 'add to my cart' para agregar productos a la orden
class CreateOrderProductView(LoginRequiredMixin, CreateView):
    template_name = 'orders/create_order_product.html'
    form_class = OrderProductForm # Formulario para agregar productos a la orden
    success_url = reverse_lazy('my_order')

    # Metodo que verifica si la orden ya existe o si se debe crear una nueva.
    def form_valid(self, form):
        # Obtener la orden activa del usuario o crear una nueva si no existe con get_or_create
        order, _ = Order.objects.get_or_create(
            is_active=True,
            user = self.request.user,
        )
        # Asignamos la orden a la instancia del formulario y la cantidad
        form.instance.order = order
        form.instance.quantity = 1
        form.save()
        return super().form_valid(form) 
    
class OrderAPI(APIView):

    authentication_classes = []
    permission_classes = []

    def get(self, request):
        orders = Order.objects.all()
        serializer = OrderSerializer(orders, many=True)
        return Response(serializer.data)

coffe_shop/products/views.py
from django.urls import reverse_lazy
from django.views import generic
from rest_framework.views import APIView
from rest_framework.response import Response

from .forms import ProductForm
from .models import Product
from .serializers import ProductSerializer


class ProductFromView(generic.FormView):
    template_name = "products/add_product.html"
    form_class = ProductForm
    success_url = reverse_lazy(
        "add_product"
    )  # cuando el producto este creado, redirigira al url especificado

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ProductListView(generic.ListView):
    model = Product
    template_name = "products/list_product.html"
    context_object_name = "products"  # nombre del contexto que se pasara al template


# Vista que muestra la lista de productos en formato JSON
class ProductListAPI(APIView):
    # Sin autenticacion
    authentication_classes = []
    permission_classes = []

    # Modificamos el metodo get para que devuelva la lista de productos en formato JSON
    def get(self, request):
        products = Product.objects.all()
        serializer = ProductSerializer(
            products, many=True
        )  # many para que el serializer sepa que es una lista
        return Response(
            serializer.data
        )  # devuelve la lista de productos en formato JSON

    def post(self, request):
        serializer = ProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=201)
        return Response(serializer.errors, status=400)

coffe_shop/users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy

class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')

coffe_shop/orders/templates/orders/my_order.html
{% extends "base.html" %} {% block content %}

<div class="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-md">
  <h2 class="text-2xl font-bold mb-4">Detalles de la Orden</h2>
  <div class="mb-2">
    <span class="text-lg font-semibold">Usuario: </span>
    <span class="text-lg">{{ order.user.username|title }}</span>
  </div>
  <div class="mb-2">
    <span class="text-lg font-semibold">Fecha de la Orden: </span>
    <span class="text-lg">{{ order.order_date|date:"F j, Y H:m" }}</span>
  </div>

  <div class="mt-6">
    <h3 class="text-xl font-bold mb-2">Artículos en tu orden:</h3>
    {% for product_order in order.orderproduct_set.all %}
    <div class="flex justify-between items-center py-2 border-b">
      <div class="text-lg">{{ product_order.product.name }}</div>
      <div class="text-lg font-semibold">{{ product_order.product.price }}</div>
    </div>
    {% empty %}
    <div class="text-red-500">No hay artículos en tu orden</div>
    {% endfor %}
  </div>
</div>

{% endblock content %}

coffe_shop/products/templates/products/add_product.html
<form action="{% url "add_product" %}" method= "post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Agregar</button>
</form>

coffe_shop/products/templates/products/list_product.html
{% extends "base.html" %} {% block content %}
<h1 class="text-3xl font-bold underline">Lista de productos</h1>
<ul>
  {% for product in products %}
  <a href="#" class="group relative inline-block overflow-hidden">
    <button
      class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-gray-900 transition hover:text-gray-900/75"
    >
      <span class="sr-only">Wishlist</span>

      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor"
        class="size-4"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
        />
      </svg>
    </button>
    {% if product.photo %}
    <img
      src="{{product.photo.url}}"
      alt="{{product.name}}"
      class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"
    />
    {% endif %}

    <div class="relative border border-gray-100 bg-white p-6">
      <span
        class="bg-yellow-400 px-3 py-1.5 text-xs font-medium whitespace-nowrap"
      >
        New
      </span>

      <h3 class="mt-4 text-lg font-medium text-gray-900">{{product.name}}</h3>

      <p class="mt-1.5 text-sm text-gray-700">${{product.price}}</p>
        <form action ="{% url "add_product" %}" class="mt-4" method = "post">
          {% csrf_token %}
          <input type="hidden" name="product" value = "{{product.id}}">
          <button
            class="block w-full rounded-sm bg-yellow-400 p-4 text-sm font-medium transition hover:scale-105"
          >
            Add to Cart
          </button>
        </form>
    </div>
  </a>
  {% endfor %}
</ul>

{% endblock content %}

coffe_shop/users/templates/users/login.html
{% extends "base.html" %} {% load tailwind_filters%} {% block content %}
<div class="container mx-auto w-1/3">
  <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Iniciar sesión</h1>
  <form action="" method="post" class="my-8">
      {% csrf_token %}
      {{ form|crispy }}
      <button
          class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500" 
          type="submit">
          Login
      </button>
  </form>
  <p class="text-center text-sm text-gray-500 mt-4">
      ¿No tienes una cuenta?
      <a class="underline" href="{% url "register" %}">Registrate</a>
  </p>
</div>
{% endblock content %}

coffe_shop/users/templates/users/register.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="container mx-auto w-1/3">
    <h1 class="text-2xl font-bold text-gray-900 sm:text-3xl">Iniciar sesión</h1>
    <form action="" method="post" class="my-8">
        {% csrf_token %}
        {{ form|crispy }}
        <button
            class="inline-block rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500" 
            type="submit">
            Registrarse
        </button>
    </form>
    <p class="text-center text-sm text-gray-500 mt-4">
        Ya tienes una cuenta
        <a class="underline" href="{% url "login" %}">Inicia sesión</a>
    </p>
</div>
{% endblock content %}